FROM python:3.10-slim

WORKDIR /app

# Installing parallel computing libraries which is used by lightgbm model. 
RUN apt-get update && apt-get install -y libgomp1

# copying contents of flask app to app folder. 
COPY flask_app/ /app/

# Copying tfidf_vectorizer to app
COPY tfidf_vectorizer.pkl /app/tfidf_vectorizer.pkl

# Generating requirements.txt. 
RUN pip install -r requirements.txt

# Installing required Libraries. 
RUN python -m nltk.downloader stopwords wordnet

EXPOSE 5000

CMD ["python", "app.py"]

